# Generated by Django 4.2.2 on 2023-06-12 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdCampaigns',
            fields=[
                ('campaign_id', models.AutoField(primary_key=True, serialize=False)),
                ('campaign_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('target_audience', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_url', models.URLField()),
                ('target_demographics', models.JSONField()),
                ('target_behavior', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='AdImpresssions',
            fields=[
                ('impression_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_identifier', models.CharField(max_length=255)),
                ('impression_time', models.DateTimeField(auto_now_add=True)),
                ('click_time', models.DateTimeField(blank=True, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.advertisement')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adcampaigns')),
            ],
        ),
    ]
